extends Node

enum ImageType {RGB, GRAYSCALE, THRESHOLD}
enum ThresholdTypes {THRESH_BINARY = 0, THRESH_BINARY_INV = 1, THRESH_TRUNC = 2, THRESH_TOZERO = 3, THRESH_TOZERO_INV = 4, THRESH_MASK = 7, THRESH_OTSU = 8, THRESH_TRIANGLE = 16, THRESH_DRYRUN = 128}
